language: go

go:
  - "1.11.x"

services:
  - docker

install: go get -t -v ./...

script: 
  - go build
  - make

deploy: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release