services:
  ysnp:
    build: .
    image: ${IMAGE:-docker.io/virtualpete/ysnp:latest}
    ports:
      - "80:8080"
    environment:
      PORT: "8080"
      STATUS: "301"
      TARGET_PROTO: "https"
      LOG: "json,info"
